### ISSUE TITLE
ClassMethods::read is conflicting with some other plugins

### ISSUE THREAD

**Issue by xlash** [jongilbraith/simple-private-messages#1]
I recommend changing the read method name to something more concreate that will not conflict, like read_message.

Thanks for the useful plugin!

**Comment by safarista** [comment]
I am looking at it as well. I thought "read" was a reserved word in Ruby? hmmm!

**Comment by safarista** [comment]
Am changing this to `ClassMethods::read_message` and `ClassMethods::message_read?` anyone has some suggestions?

**Comment by safarista** [comment]
Ok done.
