### ISSUE TITLE
Trying to Install

### ISSUE THREAD

**Issue by rancesvinto** [jongilbraith/simple-private-messages#11]
Hi,
I'm trying to install this plugin but I can't! :S

When I tried 
sudo rails generate simple_private_messages:scaffold Usuario Message
or 
rails generate simple_private_messages:model Usuario Message

The answer was in both cases :

Could not find generator simple_private_messages:model. (or :scaffold)

Could anybody help me?

(Sorry if it's a very beginner question..)

Thanks
Alberto

**Comment by jongilbraith** [comment]
Just tried it myself on a dummy project and it works file (straight copy / paste of what you've supplied).

If you issue 'rails generate' do they appear in the list of generators?

Have you maybe set it up as a submodule and not checked it out?

**Comment by rancesvinto** [comment]
Hi, Thanks for you soon reply.
First of all, I forgot tell you that I'm using Rails 3.0.

Finally I installed it. To get it, i had to do:
- insert in the project's gemfile:
  gem 'simple-private-messages', '0.0.0', :git => 'git://github.com/professionalnerd/simple-private-messages.git'

After that I could use the model and scaffold generator.
- To try it I had to add in routes.rb file:
  resources :messages

After this I think it will works but in my case I continued with errors because I use devise authentication. I tried to adapt the message model and views but it was impossible for me solve all the errors

Thanks a lot anyway for your help!!

**Comment by jongilbraith** [comment]
I've not used this in a new project for ages and someone else did the Rails 3 upgrade, so unfortunately I'm not in a great position to help.

I will however be doing this this week, so I'll be sorting all the outstanding pull requests and will then hopefully be able to help more after that.

It might be easier to conduct this over email so feel free to mail me - email is on my profile.

Cheers,

Jon

**Comment by safarista** [comment]
@jongilbraith do you mind handing over the repo to me so I could maintain it? I have the time on my hands and its such an awesome project.

**Comment by jongilbraith** [comment]
@safarista that would be great and much appreciated.

I'll drop you a message to coordinate the hand over.

**Comment by safarista** [comment]
Thanks am now pulling and pushing. Any more problems let me know.
