### ISSUE TITLE
DEPRECATION WARNING: class_inheritable_attribute is deprecated, please use class_attribute method instead

### ISSUE THREAD

**Issue by homanchou** [jongilbraith/simple-private-messages#14]
Getting Warning:

DEPRECATION WARNING: class_inheritable_attribute is deprecated, please use class_attribute method instead. Notice their behavior are slightly different, so refer to class_attribute documentation first. (called from has_private_messages at
/vendor/plugins/simple-private-messages/lib/has_private_messages_extensions.rb:17)

Using rails 3.1.1

**Comment by dcalhoun** [comment]
+1

**Comment by safarista** [comment]
Done
