### ISSUE TITLE
Question: Conversation

### ISSUE THREAD

**Issue by davidslvto** [jongilbraith/simple-private-messages#16]
Hi, is there a way to show all the messages in a conversation way?

like: 

1st message
reply message
reply of reply message

Thank you

**Comment by safarista** [comment]
dunno. Bump

**Comment by davidslvto** [comment]
Hum, I changed this gem for has_mailbox

**Comment by jordanmichaelrushing** [comment]
Personally I found has_mailbox to be way to much. I enjoy the simplicity of this app. Implimented it pretty well in and will be working on a conversation method and view if I can. Just started RoR a couple months ago, so wish me luck!
