### ISSUE TITLE
unread_message_count Error

### ISSUE THREAD

**Issue by den-plugins** [jongilbraith/simple-private-messages#20]
user.unread_message_count
NoMethodError: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.[]
    from ...rvm/gems/ruby-1.9.2-p290/bundler/gems/simple-private-messages-7461f5a05fc9/lib/has_private_messages_extensions.rb:51:in `unread_message_count'

**Comment by safarista** [comment]
Hi, could you post some more information on this issue.

the above does not help me reproduce the error. Thanks

**Comment by gretch** [comment]
Thanks. This is working fine, just an upgrade issue on my end.
