### ISSUE TITLE
bundle-install-error

### ISSUE THREAD

**Issue by ehtb** [jongilbraith/simple-private-messages#7]
just a heads up, with solution:
http://stackoverflow.com/questions/3951869/bundle-install-error
cheers

**Comment by ghost** [comment]
Not working for me.  I get the Passenger [3.0.5] error below.  This occurs on OSX 10.6 and Ubuntu 10.10.  Ruby 1.9.2 on Rails 3.0.5:

```
*** Exception PhusionPassenger::UnknownError in
PhusionPassenger::ClassicRails::ApplicationSpawner
(git://github.com/professionalnerd/simple-private-messages.git
(at master) is not checked out. Please run `bundle install`
(Bundler::GitError)) (process 83718, thread #<Thread:0x0000010086f690>):
```

I have run `bundle install` a number of times, and even deleted Gemfile.lock in between. I have tried changing the version number in Gemfile to '0.0.0' and '1.0.0'. No effect.

There is no `simple-private-messages` in `gem list`, but it _does_ exist at the top of Gemfile.lock.

**Comment by ghost** [comment]
I noticed that the gem installed itself into an odd path, a `bundler/gems` subpath, and it has some sort of ID appended to the dir name:

```
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/bundler/gems/simple-private-messages-7461f5a05fc9
```

It is the only gem in that path.  The rest of my gems are in:

```
/usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1/gems
```

I copied it to the conventional `gems` path and renamed the dir to `simple-private-messages`. Restarted passenger standalone, and it still doesn't work. The same error appears as sone as I refresh the site.

**Comment by ghost** [comment]
Solution:
http://stackoverflow.com/questions/3605235/rails-3-passenger-cant-find-git-gems-installed-by-bundler

Which, for me, meant:

```
cd /Library/WebServer/Documents/MyRailsApp
nano .bundle/config
```

Add line:

```
BUNDLE_PATH: /usr/local/Cellar/ruby/1.9.2-p180/lib/ruby/gems/1.9.1
```

Run `bundle` again. (You may want to delete Gemfile.lock first.) In my case, it completely reinstalled every gem in Gemfile again.

This would only work by adding it to `.bundle/config`. Would **not** work adding `BUNDLE_PATH` to `/etc/profile` or anything like that.

**Comment by safarista** [comment]
Looks like this is sorted. Let me know if you have a problem.
